Fix multi-containers options
containers/ansible-podman-collections pull request #258
Opened 2021-05-14 11:30 UTC by sshnaidm

2021-05-14 21:29 UTC, sshnaidm commented
@mwhahaha  please take a look, testing here: https://review.rdoproject.org/r/c/testproject/+/33683

2021-05-15 16:02 UTC, sshnaidm commented
github-check

2021-05-18 17:59 UTC, sshnaidm commented
github-check

2021-05-18 17:59 UTC, sshnaidm commented
check-github

2021-05-18 18:11 UTC, mwhahaha requested changes
Looks ok, i've been testing something similar pulled into my module directly.
 https://review.opendev.org/c/openstack/tripleo-ansible/+/791317/7/tripleo_ansible/ansible_plugins/modules/tripleo_container_manage.py@153

Not certain if we want to include this here or make the expectation that these things would be handled by something outside of this.

2021-05-19 05:39 UTC, sshnaidm commented
> Looks ok, i've been testing something similar pulled into my module directly.
> https://review.opendev.org/c/openstack/tripleo-ansible/+/791317/7/tripleo_ansible/ansible_plugins/modules/tripleo_container_manage.py@153
> 
> Not certain if we want to include this here or make the expectation that these things would be handled by something outside of this.

Well, arguments types issue is definitely a bug in `podman_containers` module and should be fixed here. I think functions `_container_opts_defaults`, `_container_opts_update` and `_container_opts_types` can be handled here.

2021-05-24 06:58 UTC, merged