Add support for podman pod create --infra-name
containers/ansible-podman-collections pull request #292
Opened 2021-08-30 15:06 UTC by mskarbek

Fixes: #291

2021-08-31 11:17 UTC, sshnaidm requested changes

2021-08-31 11:17 UTC, sshnaidm commented on plugins/modules/podman_pod.py
> +    - The name that will be used for the pod’s infra container.
`pod’s` throws an error:

```diff
ERROR: plugins/modules/podman_pod.py:105:45: use ASCII quotes `'` and `"` instead of Unicode quotes
```

2021-08-31 12:04 UTC, mskarbek commented on plugins/modules/podman_pod.py
> +    - The name that will be used for the pod’s infra container.
Fixed

2021-09-01 10:41 UTC, sshnaidm approved these changes

2021-09-01 10:42 UTC, merged