Support --new in generate_systemd
containers/ansible-podman-collections pull request #334
Opened 2021-11-14 10:20 UTC by lbeltrame

Fixes #318.

Currently it's set independently from `remove`.

2021-11-16 18:58 UTC, sshnaidm commented
Need to add it to documentation: https://github.com/containers/ansible-podman-collections/blob/a8e81193f49d42866bdb893864dc27d96fc400b4/plugins/modules/podman_container.py#L294-L353

Also please see the discussion in #318

2021-11-16 18:59 UTC, sshnaidm requested changes
need to add to docs: https://github.com/containers/ansible-podman-collections/blob/a8e81193f49d42866bdb893864dc27d96fc400b4/plugins/modules/podman_container.py#L294-L353

2021-11-16 22:33 UTC, lbeltrame commented
Thanks for the review. Somehow I missed the responses: I'll get it done and update this PR.

2021-11-18 10:56 UTC, sshnaidm approved these changes

2021-11-18 12:35 UTC, merged

2021-11-18 14:32 UTC, zephyros-dev commented
The generate systemd command is used in both container and pod module, so the docs in the pod module should also be updated. Should a commit be made here or in a new PR @sshnaidm?

2021-11-18 14:49 UTC, sshnaidm commented
@zephyros-dev please make a new PR, I've merged that one. Thanks, nice catch!