Added cpu_quota parameter and fixed #559
containers/ansible-podman-collections pull request #581
Opened 2023-04-17 15:16 UTC by zarath

2023-08-02 15:30 UTC, sshnaidm requested changes
Thanks for the contribution! A few questions are inside though.

2023-08-02 15:30 UTC, sshnaidm commented on plugins/module_utils/podman/podman_container_lib.py
> +            image_ports = self.image_info.get(
Let's not change not related code (we have 120 chars lines in Ansible allowed)

2023-08-02 16:17 UTC, zarath commented on plugins/module_utils/podman/podman_container_lib.py
> +        # if cpu_period left to default keep settings
One can argue if it is more expected not to change an undefined parameter in a second run with different settings, or reset to default.
Personally I would prefer first.
I mean, if I intentionally use a parameter, I would require to set it back if I want to have a change.

It's a little more complex to ignore before as you have to view on both related parameters..

2023-08-02 17:10 UTC, zarath commented on plugins/module_utils/podman/podman_container_lib.py
> +        # if cpu_period left to default keep settings
They are related.
If I don't add the new parameter, the fix will not work.
https://docs.podman.io/en/latest/markdown/podman-run.1.html
> --cpus Number of CPUs. The default is 0.0 which means no limit. This is shorthand for --cpu-period and --cpu-quota, therefore the option cannot be specified with --cpu-period or --cpu-quota.
> 

To reach idempotency all cases have to be solved as info returns both representations, no matter if any parameter was given. As soon as you put one in the other appears in the delta.

2023-08-02 19:55 UTC, sshnaidm commented on plugins/module_utils/podman/podman_container_lib.py
> +        # if cpu_period left to default keep settings
Sorry, I struggle to understand how exactly they are related. If you remove all with `cpu_quota` from your patch, it still fixes the idempotency issue, you can check it with simple task running twice:
```yaml
    - name: Create test container
      containers.podman.podman_container:
        name: test
        image: alpine:3.16
        state: present
        command: sleep 1h
        cpus: 2.0
```

2023-08-02 19:58 UTC, sshnaidm commented on plugins/module_utils/podman/podman_container_lib.py
> +        # if cpu_period left to default keep settings
I suggested we merge the fix for current issue, and then merge addition of `cpu_quota`, that's it.

2023-08-03 06:40 UTC, zarath commented on plugins/module_utils/podman/podman_container_lib.py
> +        # if cpu_period left to default keep settings
done

2023-08-03 12:28 UTC, sshnaidm approved these changes
Awesome, thanks!

2023-08-03 12:29 UTC, merged