Add podman_runlabel module This is implementing the [podman container runlabel](https://docs.podman.io/en/latest/markdown/podman-container-runlabel.1.html) command.
containers/ansible-podman-collections pull request #626
Opened 2023-08-17 06:45 UTC by pdostal

This is to implement the [podman container runlabel](https://docs.podman.io/en/latest/markdown/podman-container-runlabel.1.html) command.

2023-08-17 10:46 UTC, sshnaidm commented
Great! Thanks for working on this.
Please fix the CI issues:
```
ERROR: Found 1 shebang issue(s) which need to be resolved:
ERROR: plugins/modules/podman_runlabel.py:0:0: module should not be executable
```
Also need to sign the commit to make DCO job happy, you can do with `git commit --amend -s`

2023-08-17 10:49 UTC, sshnaidm requested changes

2023-08-17 10:49 UTC, sshnaidm commented on plugins/modules/podman_runlabel.py
> +- containers.podman.podman_label:
typo
```suggestion
- containers.podman.podman_runlabel:
```

2023-08-21 16:56 UTC, sshnaidm commented
I think it still has an issue:
```
ERROR: Found 1 shebang issue(s) which need to be resolved:
ERROR: plugins/modules/podman_runlabel.py:0:0: module should not be executable
```

Can you make `chmod -x plugins/modules/podman_runlabel.py`?

2023-08-22 13:47 UTC, sshnaidm approved these changes

2023-08-22 13:47 UTC, merged

2023-08-22 13:48 UTC, sshnaidm commented
Thanks for contribution! Next step will be creating tests :)

2023-08-22 14:03 UTC, pdostal commented
@sshnaidm I might try to help with it but I would appreciate some tutorial how to run the tests locally.